// <auto-generated />
using System;
using Kurs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kurs.Migrations
{
    [DbContext(typeof(CarServiceContext))]
    [Migration("20260305094324_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kurs.Models.Customer", b =>
                {
                    b.Property<int>("ID_Customers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Customers"));

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Middle_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID_Customers");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Kurs.Models.Employee", b =>
                {
                    b.Property<int>("ID_Employees")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Employees"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Middle_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Employees");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Kurs.Models.Part", b =>
                {
                    b.Property<int>("ID_Parts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Parts"));

                    b.Property<int?>("ID_Suppliers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ID_Parts");

                    b.HasIndex("ID_Suppliers");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("Kurs.Models.Supplier", b =>
                {
                    b.Property<int>("ID_Suppliers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Suppliers"));

                    b.Property<string>("Contact_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID_Suppliers");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Kurs.Models.User", b =>
                {
                    b.Property<int>("ID_Users")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Users"));

                    b.Property<int>("ID_Employees")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Users");

                    b.HasIndex("ID_Employees")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Kurs.Models.Vehicle", b =>
                {
                    b.Property<int>("ID_Vehicles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Vehicles"));

                    b.Property<string>("Brand")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ID_Customers")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Plate_Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("ID_Vehicles");

                    b.HasIndex("ID_Customers");

                    b.HasIndex("VIN")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Kurs.Models.WorkOrder", b =>
                {
                    b.Property<int>("ID_WorkOrders")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_WorkOrders"));

                    b.Property<DateTime?>("Date_Close")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_Open")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Customers")
                        .HasColumnType("int");

                    b.Property<int>("ID_Vehicles")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Открыт");

                    b.HasKey("ID_WorkOrders");

                    b.HasIndex("ID_Customers");

                    b.HasIndex("ID_Vehicles");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("Kurs.Models.WorkOrderEmployee", b =>
                {
                    b.Property<int>("ID_WorkOrderEmployees")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_WorkOrderEmployees"));

                    b.Property<int>("ID_Employees")
                        .HasColumnType("int");

                    b.Property<int>("ID_WorkOrders")
                        .HasColumnType("int");

                    b.HasKey("ID_WorkOrderEmployees");

                    b.HasIndex("ID_Employees");

                    b.HasIndex("ID_WorkOrders", "ID_Employees")
                        .IsUnique();

                    b.ToTable("WorkOrderEmployees");
                });

            modelBuilder.Entity("Kurs.Models.WorkOrderPart", b =>
                {
                    b.Property<int>("ID_WorkOrderParts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_WorkOrderParts"));

                    b.Property<int>("ID_Parts")
                        .HasColumnType("int");

                    b.Property<int>("ID_WorkOrders")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Unit_Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ID_WorkOrderParts");

                    b.HasIndex("ID_Parts");

                    b.HasIndex("ID_WorkOrders");

                    b.ToTable("WorkOrderParts");
                });

            modelBuilder.Entity("Kurs.Models.WorkOrderService", b =>
                {
                    b.Property<int>("ID_WorkOrderServices")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_WorkOrderServices"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ID_WorkOrders")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ID_WorkOrderServices");

                    b.HasIndex("ID_WorkOrders");

                    b.ToTable("WorkOrderServices");
                });

            modelBuilder.Entity("Kurs.Models.Part", b =>
                {
                    b.HasOne("Kurs.Models.Supplier", "Supplier")
                        .WithMany("Parts")
                        .HasForeignKey("ID_Suppliers")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Kurs.Models.User", b =>
                {
                    b.HasOne("Kurs.Models.Employee", "Employee")
                        .WithOne("User")
                        .HasForeignKey("Kurs.Models.User", "ID_Employees")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Kurs.Models.Vehicle", b =>
                {
                    b.HasOne("Kurs.Models.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("ID_Customers")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Kurs.Models.WorkOrder", b =>
                {
                    b.HasOne("Kurs.Models.Customer", "Customer")
                        .WithMany("WorkOrders")
                        .HasForeignKey("ID_Customers")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kurs.Models.Vehicle", "Vehicle")
                        .WithMany("WorkOrders")
                        .HasForeignKey("ID_Vehicles")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Kurs.Models.WorkOrderEmployee", b =>
                {
                    b.HasOne("Kurs.Models.Employee", "Employee")
                        .WithMany("WorkOrderEmployees")
                        .HasForeignKey("ID_Employees")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kurs.Models.WorkOrder", "WorkOrder")
                        .WithMany("WorkOrderEmployees")
                        .HasForeignKey("ID_WorkOrders")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("Kurs.Models.WorkOrderPart", b =>
                {
                    b.HasOne("Kurs.Models.Part", "Part")
                        .WithMany("WorkOrderParts")
                        .HasForeignKey("ID_Parts")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kurs.Models.WorkOrder", "WorkOrder")
                        .WithMany("WorkOrderParts")
                        .HasForeignKey("ID_WorkOrders")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("Kurs.Models.WorkOrderService", b =>
                {
                    b.HasOne("Kurs.Models.WorkOrder", "WorkOrder")
                        .WithMany("WorkOrderServices")
                        .HasForeignKey("ID_WorkOrders")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("Kurs.Models.Customer", b =>
                {
                    b.Navigation("Vehicles");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("Kurs.Models.Employee", b =>
                {
                    b.Navigation("User");

                    b.Navigation("WorkOrderEmployees");
                });

            modelBuilder.Entity("Kurs.Models.Part", b =>
                {
                    b.Navigation("WorkOrderParts");
                });

            modelBuilder.Entity("Kurs.Models.Supplier", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("Kurs.Models.Vehicle", b =>
                {
                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("Kurs.Models.WorkOrder", b =>
                {
                    b.Navigation("WorkOrderEmployees");

                    b.Navigation("WorkOrderParts");

                    b.Navigation("WorkOrderServices");
                });
#pragma warning restore 612, 618
        }
    }
}
